export const WEAPON_TRAITS: Record<string, string> = {
  'Accurate': '+1 to hit at long range.',
  'Backstab': '+1 Strength when attacking from outside the target\'s vision arc.',
  'Blast (3")': 'Uses a 3" Blast marker. All models under the marker are hit.',
  'Blast (5")': 'Uses a 5" Blast marker. All models under the marker are hit.',
  'Blaze': 'Target catches fire on 4+. When activated: suffer S3 AP-1 hit, move 2D6" random, roll 6+ to extinguish.',
  'Burrowing': 'Can target outside LOS. Place Blast anywhere, scatter 2D6". Hits resolve in End phase.',
  'Chem Delivery': 'Declare chem type. Roll >= Toughness to inflict dose instead of wound roll.',
  'Combi': 'Two profiles. Pick one per attack. Roll twice for Ammo, apply worst. Some weapons gain Unstable or Single Shot.',
  'Capture': 'If this weapon takes an enemy Out of Action, they are automatically Captured instead of rolling on the Lasting Injury table.',
  'Concussion': '-2 Initiative until end of round.',
  'Cursed': 'Target must pass Willpower test when hit or become Insane.',
  'Defoliate': 'D3 damage to Carnivorous Plants. Removes Brainleaf Zombies on Out of Action.',
  'Demolition': 'Can attack scenery (doors/objectives) in close combat. Single auto-hit.',
  'Demolitions': 'Can be used to attack doors and objectives. Always hits scenery automatically.',
  'Digi': 'Ring/glove weapon. Grants extra attack. Doesn\'t count toward weapon limit. Max 10 per fighter.',
  'Disarm': 'On hit roll of 6, target can only make unarmed Reaction attacks this round.',
  'Drag': 'If hit and not Out of Action, roll D6 >= target\'s Strength to drag D3" toward attacker.',
  'Entangle': 'Hits can\'t be Parried. On hit roll of 6, target\'s Reactions suffer -2.',
  'Esoteric': 'Xenos/Corrupted weapon. Cannot take accessories or be modified.',
  'Fear': 'Target must pass Nerve test at -2 or become Broken instead of Injury roll.',
  'Fixed': 'Weapon on own base. Fighter B2B can use Double action to move it, then fire.',
  'Flare': 'Target becomes Revealed. Blast stays on board, revealing models it touches. Removed on 4+ in End phase.',
  'Flash': 'Instead of wound roll, target passes Initiative or becomes Blind. Not Ready, Reactions hit on 6 only.',
  'Gas': 'Roll >= Toughness to inflict Injury roll. No save. Not Pinned when hit. Vehicles use Rear Toughness.',
  'Graviton Pulse': 'Target passes Strength test or suffers damage. No save. Blast stays as difficult terrain.',
  'Grenade': 'Thrown with Shoot (Basic). Range = Strength x2. Always Ammo test, no Firepower dice. Can\'t reload.',
  'Gunk': '-1" Movement, no +D3" charge bonus, -1 Initiative. Catches fire on 2+ from Blaze. Ends in End phase.',
  'Haemophagic': '+1 to Toxin roll if target was previously hit by this weapon.',
  'Hexagrammatic': 'Ignores Psychic saves. 2x damage vs Psykers.',
  'Impale': 'Projectile continues through wounded target. Hits fighters within 1" of line, -1 Str per hit.',
  'Knockback': 'If hit roll >= target\'s Strength, push 1" away. +1 Damage if trapped. May follow up in melee.',
  'Lance': '+1 Strength while Mounted when Charging or Ride By.',
  'Limited': 'When Out of Ammo, that ammo type is permanently lost. Can reload other profiles.',
  'Master-crafted': 'Once per battle, re-roll a failed hit roll.',
  'Melee': 'Can be used in close combat. Range E (Engaged).',
  'Melta': 'At short range: Fighters reduced to 0 wounds auto Out of Action. Vehicles +1 damage dice.',
  'Paired': 'Counts as dual weapons for Attacks. Doubles base Attacks when charging.',
  'Parry': 'Force attacker to re-roll one successful hit. Two Parry weapons = two re-rolls.',
  'Phase': 'Ignores armor and field armor saves.',
  'Plentiful': 'Ammo tests automatically pass when reloading.',
  'Power': 'Can\'t be Parried except by Power weapons. On 6 to hit: ignores saves (except Fields), +1 Damage.',
  'Power Pack': '0-2 per fighter. No weapon slot. If Melee, grants +1 attack.',
  'Pulverise': 'After Injury roll, roll D6. If >= Toughness or 6: change Flesh Wound to Serious Injury.',
  'Rad-phage': 'After resolving hits, roll 4+ per hit fighter to inflict a Flesh Wound.',
  'Rapid Fire (1)': 'Successful hit scores hits = bullet holes on Firepower dice. Roll up to 1 dice.',
  'Rapid Fire (2)': 'Successful hit scores hits = bullet holes on Firepower dice. Roll up to 2 dice.',
  'Rapid Fire (3)': 'Successful hit scores hits = bullet holes on Firepower dice. Roll up to 3 dice.',
  'Reckless': 'Ignores Target Priority. Randomize target from all eligible (friend & foe).',
  'Rending': 'On wound roll of 6+: +1 Damage (Fighters) or +1 Damage dice (Vehicles).',
  'Scarce': 'Can\'t be reloaded. Once Out of Ammo, can\'t use this weapon again this battle.',
  'Scattershot': 'If hit, inflict D6 wound rolls instead of 1.',
  'Seismic': 'Wound roll of 6 ignores saves. Target always Pinned. Vehicles test Hnd or Lose Control.',
  'Sever': 'Injury rolls are automatically Out of Action.',
  'Assault Shield': 'Compact combat shield. +2 save vs Melee, +1 save vs Ranged in front arc. Can be used alongside a pistol.',
  'Shield': '+2 save vs Melee, +1 save vs Ranged from front 90°.',
  'Shield Breaker': 'Ignores shields. Field armors roll twice, apply lowest.',
  'Shock': 'On hit roll of 6, the attack automatically wounds.',
  'Shred': 'On wound roll of 6, double the AP.',
  'Sidearm': 'Pistol usable in close combat. Two Sidearms can fire together at -1 to hit.',
  'Silent': 'Sneak Attack: No alarm test. Pitch Black: Hidden fighter stays hidden.',
  'Single Shot': 'Can only fire once per battle. Auto-fails Ammo after use.',
  'Smoke': 'No hits or wounds. Creates 2.5" cloud blocking LOS. Removed on 5+ in End phase.',
  'Template': 'Uses Flame template. All models under template are hit.',
  'Terrifying': 'Enemies must pass Willpower test to attack the wearer in close combat.',
  'Toxin': 'Roll >= Toughness to inflict Injury roll. Armor saves apply. Doesn\'t affect vehicles.',
  'Twin-linked': 'Re-roll any number of Ammo dice.',
  'Unstable': 'On Ammo symbol, roll 4+ or suffer catastrophic overload (Out of Action for fighters).',
  'Unreliable': 'On failed Ammo test, the weapon is destroyed and removed from the fighter.',
  'Unwieldy': 'Takes 2 weapon slots. Shoot is Double action. Melee needs 2 hands.',
  'Versatile': 'Melee weapon with reach. Can attack without B2B from within Long range.',
  'Vortex': 'Blast stays. Each End phase roll D3: 1=remove, 2=stay and hit, 3=scatter D6+2" hitting all in path.',
  'Web': 'Wound = auto Seriously Injured (Webbed). No save. Recovery: Flesh Wound frees, SI stays webbed, OOA may be Captured.',
};
